In [7]:
import keras as K
import tensorflow as tf
import numpy as np

In [43]:
zero = tf.zeros(1)

In [46]:
z = tf.constant([True])

In [40]:
zero

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [20]:
A = tf.constant([[1.0, 2.0], [3.0, 4.0]])
A

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [28]:
B = tf.constant([[True, True], [False, True]],dtype = tf.bool)
B

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [False,  True]])>

In [50]:
t = A>0
t

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [70]:
%time
# p = B>0
p = tf.cast(B,tf.int32)>0
p

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 10 µs


<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [False,  True]])>

In [76]:
p = B==True
p

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [False,  True]])>